### ISSUE TITLE
version 4.1.1 error - undefined object

### ISSUE THREAD

**Issue by kby799** [Nexxa/cordova-base64-to-gallery#9]
> Undefined symbols for architecture i386:
>   "_CACurrentMediaTime", referenced from:
>       ___42-[Base64ToGallery saveImageDataToLibrary:]_block_invoke in Base64ToGallery.o
> ld: symbol(s) not found for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

After updated to 4.1.1, I found this error. Hope someone could look into this, thank you.

**Comment by StefanoMagrassi** [comment]
@kby799 do you have additional information from log?

**Comment by kby799** [comment]
> *\* BUILD FAILED **
> 
> The following build commands failed:
>   Ld /volumes/helloWorld/ionic/final/working\ version/simple-login/platforms/ios/build/emulator/HelloWorld.app/HelloWorld normal i386
> (1 failure)
> Error code 65 for command: xcodebuild with args: -xcconfig,/volumes/helloWolrd/ionic/final/working version/simple-login/platforms/ios/cordova/build-debug.xcconfig,-project,HelloWorld.xcodeproj,ARCHS=i386,-target,HelloWorld,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/volumes/helloWorld/ionic/final/working version/simple-login/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/volumes/helloWorld/ionic/final/working version/simple-login/platforms/ios/build/sharedpch
> Error: /volumes/helloWorld/ionic/final/working version/simple-login/platforms/ios/cordova/build: Command failed with exit code 2

This is all I have

**Comment by 3lviend** [comment]
@kby799 You can try to update or re-add cordova-ios with version 4.0.0:

cordova platform add ios@4.0.0

and try to remove platform and re-add or run ionic build ios.

Thanks

**Comment by kby799** [comment]
@3lviend Thanks for your help, but I don't have access to the project anymore.
